# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rate My Class' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rate My Class
  pod 'AFNetworking'
  pod 'Parse'
  pod "TTGTagCollectionView"
  pod 'DateTools'

end
